name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
       name: vendor
       path: vendor

  psalm:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Download vendor artifact
        uses: actions/download-artifact@v2
        with:
          name: vendor
      - name: Run psalm validation
        run: composer run-script psalm

  test:
    runs-on: ubuntu-latest
    needs:
      - build
      - psalm
    steps:
      - uses: actions/checkout@v2
      - name: Download vendor artifact
        uses: actions/download-artifact@v2
        with:
          name: vendor
      - name: Run test suite
        run: composer run-script test
